'use strict';

const serverNames = [
  'Phoenix',
  'Tucson',
  'Scottdale',
  'Chandler',
  'Brainburg',
  'SaintRose',
  'Mesa',
  'Red-Rock',
  'Yuma',
  'Surprise',
  'Prescott',
  'Glendale',
  'Kingman',
  'Winslow',
];

const fractionNames = [
  'Полиция г. Лос-Сантос',
  'Областная полиция',
  'ФБР',
  'Полиция г.Сан-Фиерро',
  'Больница г. Лос-Сантос',
  'Правительство',
  'Тюрьма строгого режима',
  'Больница г. Сан-Фиерро',
  'Инструкторы',
  'Новостное агенство',
  'Grove Street Gang',
  'Los Santos Vagos Gang',
  'The Ballas Gang',
  'Varios Los Aztecas Gang',
  'The Rifa Gang',
  'Russian Mafia',
  'Yakuza',
  'La Cosa Nostra',
  'Warlock MC',
  'Армия г. Лос-Сантос',
  'Центральный Банк',
  'Больница г. Лас-Вентура',
  'Полиция г. Лас-Вентурас',
  'Новостное агенство ЛВ',
  'Night Wolfs',
  'Новостное агенство СФ',
  'Армия г.Сан-Фиерро',
  'Темное братство',
  'Страховая компания',
];

module.exports = {
  serverNames,
  fractionNames,
};
